version: 2.1
setup: true


orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

parameters:
  run-hello-world-p:
    type: boolean
    default: false


workflows:
  hello-world-p:
    when: << pipeline.parameters.run-hello-world-p >>
    jobs:
      - orb-tools/lint:
          source-dir: hello-world-p