version: 2.1

# Reuse a common job for publishing each orb

parameters:
  run-hello:
    type: boolean
    default: false


jobs:
  validate-orb:
    docker:
      - image: cimg/python:3.9
    description: Validate an orb
    parameters:
      path:
        type: string
        description: The path to the orb
    steps:
      - checkout
      - run:
          name: Validate orb
          command: |
            circleci orb validate << parameters.path >>/orb.yml

  publish-orb:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      - run:
          name: publish dev orb
          command: |
             circleci orb publish << parameters.path >>/orb.yml potato/<< parameters.path >>@dev:first

workflows:
  hello:
    when: << pipeline.parameters.run-hello >>
    jobs:
      - validate-orb:
          path: hello
      - publish-orb:
          path: hello
          requires:
            - validate-orb
