version: 2.1

# Reuse a common job for publishing each orb

parameters:
  run-hello-world-p:
    type: boolean
    default: false


jobs:
  validate-orb:
    description: Validate an orb
    parameters:
      path:
        type: string
        description: The path to the orb
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Validate orb
          command: |
            set -e
            circleci orb validate << parameters.path >>/orb.yml

#  publish-orb:
#    docker:
#      - image: cimg/python:3.9
#    parameters:
#      path:
#        type: string
#        description: The path to the orb
#    steps:
#      - checkout
#      - run:
#          name: publish dev orb
#          command: |
#             circleci orb publish << parameters.path >>/orb.yml potato/<< parameters.path >>@dev:first

workflows:
  hello:
    when: << pipeline.parameters.run-hello-world-p >>
    jobs:
      - validate-orb:
          path: hello-world-p
#      - publish-orb:
#          path: hello
#          requires:
#            - validate-orb
